import type{ListingInput,ListingQueueItem,ListingRecord}from'../../shared/listings';
import{unwrap}from'./inventoryService';

const checklist=(ready:boolean)=>({photosComplete:ready,primaryPhotoSelected:ready,titleComplete:true,descriptionComplete:ready,itemSpecificsComplete:ready,pricingComplete:true,shippingComplete:ready,readyToList:ready});
const record=(inventoryId:number,ready:boolean):ListingRecord=>({id:inventoryId,inventoryId,listingTitle:inventoryId===1?"Levi's 501 Men's 36x32 Indigo Straight Leg Jeans":inventoryId===2?'Nike Air Max Running Shoes Size 11':'Vintage Pendleton Wool Blend Overcoat Camel Large',description:ready?'Clean, measured, and photographed. Carefully packed by Metro Refined Racks.':'',category:inventoryId===2?'Shoes':inventoryId===3?'Coats':'Jeans',condition:inventoryId===2?'Very Good':'Excellent',brand:inventoryId===2?'Nike':inventoryId===3?'Pendleton':"Levi's",department:ready?'Men':'',size:inventoryId===2?'11':inventoryId===3?'L':'36x32',color:inventoryId===2?'White / Navy':inventoryId===3?'Camel':'Indigo',material:ready?'Cotton blend':'',style:ready?'Classic':'',type:ready?'Everyday':'',model:'',mpn:'',upc:'',countryOfManufacture:'',listPrice:inventoryId===1?39.99:inventoryId===2?64.99:119.99,minimumOffer:ready?31:0,shippingService:ready?'USPS Ground Advantage':'',shippingCharge:ready?7.99:0,handlingTime:ready?1:0,returnPolicy:ready?'30-day returns':'',ebayItemId:'',listingUrl:'',status:ready?'Ready':'Purchased',internalNotes:'RC1 workflow sample',checklist:checklist(ready),createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});
const demoQueue=():ListingQueueItem[]=>[
 {inventoryId:1,sku:'MRR-2026-000001',title:"Levi's 501 Straight Leg Jeans",brand:"Levi's",category:'Jeans',condition:'Excellent',size:'36x32',color:'Indigo',purchasePrice:12,listPrice:39.99,bin:'B-12',rack:'R1',shelf:'',drawer:'',photoCount:3,listing:record(1,true),readiness:100,missing:[]},
 {inventoryId:2,sku:'MRR-2026-000002',title:'Nike Air Max Running Shoes',brand:'Nike',category:'Shoes',condition:'Very Good',size:'11',color:'White / Navy',purchasePrice:18,listPrice:64.99,bin:'',rack:'',shelf:'S2',drawer:'',photoCount:0,listing:record(2,false),readiness:29,missing:['photos','primary photo','description','item specifics','shipping']},
 {inventoryId:3,sku:'MRR-2026-000003',title:'Vintage Wool Blend Overcoat',brand:'Pendleton',category:'Coats',condition:'Excellent',size:'L',color:'Camel',purchasePrice:24,listPrice:119.99,bin:'',rack:'R3',shelf:'',drawer:'',photoCount:3,listing:record(3,true),readiness:100,missing:[]}
];
export const listingService={async queue():Promise<ListingQueueItem[]>{if(!window.metro)return demoQueue();return unwrap(await window.metro.listings.queue())},async save(inventoryId:number,input:ListingInput){if(!window.metro)return{...record(inventoryId,input.checklist.readyToList),...input};return unwrap(await window.metro.listings.save(inventoryId,input))}};
