import type{AIProviderCapabilities,AIProviderInfo,AIRequest,AIResponse,AISuggestion,AISettings,AITask}from'../shared/ai.js';
import{buildPrompt,containsPromptInjection}from'../src/domain/aiPrompts.js';
import{missingInformation,pricingSuggestion,sourceHash,validateSuggestion}from'../src/domain/aiListing.js';
export interface AIProvider{id:string;model:string;capabilities:AIProviderCapabilities;generate(request:AIRequest,settings:AISettings,signal?:AbortSignal):Promise<AIResponse>;test(settings:AISettings):Promise<{ok:boolean;message:string}>}
const suggestion=(field:string,value:string,evidence:'verified'|'inferred'|'missing'='verified',sources:string[]=[]):AISuggestion=>({id:field+'-'+Math.random().toString(36).slice(2,8),field,value,status:'Draft',evidence,confidence:evidence==='verified'?0.92:0.65,warnings:[],sources});
const titleCandidates=(r:AIRequest)=>{const i=r.item,parts=[i.brand,i.listing.model,i.title,i.size,i.color].filter(Boolean);const base=[...new Set(parts.join(' ').split(/\s+/))].join(' ').slice(0,80);return Array.from({length:Math.min(3,r.candidateCount??3)},(_,n)=>suggestion('title',(n?base+' '+['Item','Style'][n-1]:base).slice(0,80),'verified',['brand','title','size','color']))};
function generateTask(request:AIRequest):AISuggestion[]{const i=request.item,l=i.listing,p=pricingSuggestion(request),missing=missingInformation(request);const map:Record<AITask,()=>AISuggestion[]>={title:()=>titleCandidates(request),description:()=>[suggestion('description',[i.title,'Brand: '+(i.brand||'[Missing]'),'Size: '+(i.size||'[Missing]'),'Color: '+(i.color||'[Missing]'),'Condition: '+(i.condition||'[Missing]'),'Carefully packed and shipped after purchase.'].join('\n'),'verified',['inventory fields'])],category:()=>[suggestion('category',i.category||'Unknown / Needs review',i.category?'verified':'missing',['category'])],specifics:()=>['brand','size','color','material','model'].map(field=>suggestion(field,String((l as unknown as Record<string,unknown>)[field]||(i as unknown as Record<string,unknown>)[field]||'Missing'),String((l as unknown as Record<string,unknown>)[field]||(i as unknown as Record<string,unknown>)[field])?'verified':'missing',[field])),condition:()=>[suggestion('conditionNotes',i.condition?i.condition+'. '+(i.listing.internalNotes||'Review photos and disclose all visible wear.'):'Condition details are missing.','inferred',['condition','notes'])],keywords:()=>[suggestion('keywords',[i.brand,i.category,i.size,i.color].filter(Boolean).join(', '),'verified',['brand','category','size','color'])],pricing:()=>[suggestion('pricing',p.target===null?'Insufficient data':'Low $'+p.low?.toFixed(2)+' · Target $'+p.target.toFixed(2)+' · High $'+p.high?.toFixed(2),'inferred',['purchase cost','expected price'])],shipping:()=>[suggestion('shipping','Package and weight require confirmation. Suggested handling time: 1 business day.','inferred',['category'])],missing:()=>[suggestion('missingInformation','Listing blockers: '+(missing.blockers.join(', ')||'None')+'\nImportant: '+(missing.important.join(', ')||'None')+'\nOptional: '+(missing.optional.join(', ')||'None'),'verified',['listing readiness'])],'full-draft':()=>[...titleCandidates({...request,candidateCount:1}),...map.description(),...map.category(),...map.specifics(),...map.condition(),...map.pricing(),...map.shipping(),...map.missing()]};return map[request.task]().map(validateSuggestion)}
export class LocalAIProvider implements AIProvider{id='local';model='metro-deterministic-v1';capabilities={text:true,images:false,streaming:false,usage:true};async generate(request:AIRequest,_settings:AISettings,signal?:AbortSignal){if(signal?.aborted)throw new Error('CANCELLED');buildPrompt(request);const injection=containsPromptInjection(request.item.listing.internalNotes);return{provider:this.id,model:this.model,generatedAt:new Date().toISOString(),suggestions:generateTask(request),missing:missingInformation(request).blockers,warnings:injection?['Suspicious instructions in inventory notes were ignored.']:[],usage:{estimated:true},sourceHash:sourceHash(request)}}async test(){return{ok:true,message:'Deterministic offline provider is ready.'}}}
export function providerInfo():AIProviderInfo[]{return[{id:'local',model:'metro-deterministic-v1',configured:true,offline:true,capabilities:new LocalAIProvider().capabilities},{id:'openai',model:process.env.METRO_AI_MODEL||'configurable',configured:Boolean(process.env.OPENAI_API_KEY),offline:false,capabilities:{text:true,images:true,streaming:false,usage:true}}]}
export async function generateWithRetry(request:AIRequest,settings:AISettings,signal?:AbortSignal,retries=1){let last:unknown;for(let attempt=0;attempt<=retries;attempt++){try{return await new LocalAIProvider().generate(request,settings,signal)}catch(error){last=error;if(signal?.aborted)throw error}}throw last}
