import { Activity, Boxes, CircleDollarSign, ListChecks, PackagePlus, Sparkles } from 'lucide-react';
import type { InventoryItem } from '../../../shared/inventory';
import { dashboardMetrics } from '../../domain/inventory';

const money = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(value);
export function KpiCard({ label, value, detail }: { label: string; value: string | number; detail: string }) { return <article><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>; }
export function RecentActivity({ items }: { items: InventoryItem[] }) { return <article className="panel activity-panel"><div className="section-title"><Activity size={18}/><div><h2>Recent Activity</h2><p>Latest inventory updates</p></div></div><div className="activity-list">{items.slice().sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,5).map(item=><div key={item.id}><span className={`dot ${item.status.toLowerCase()}`}/><div><b>{item.title}</b><small>{item.sku} · {item.status} · {item.bin || item.rack || 'Unassigned storage'}</small></div><time>{new Date(item.updatedAt).toLocaleDateString()}</time></div>)}</div></article>; }
export function QuickActions({ onAdd, onStatus, onAll }: { onAdd:()=>void; onStatus:(value:string)=>void; onAll:()=>void }) { return <article className="panel quick-panel"><div className="section-title"><Sparkles size={18}/><div><h2>Quick Actions</h2><p>Common inventory workflows</p></div></div><div className="quick-grid"><button onClick={onAdd}><PackagePlus/>Add inventory</button><button onClick={()=>onStatus('Draft')}><ListChecks/>Review drafts</button><button onClick={()=>onStatus('Sold')}><CircleDollarSign/>Review sales</button><button onClick={onAll}><Boxes/>View all stock</button></div></article>; }
export function DashboardPage({ items, onAdd, onStatus, onAll }: { items:InventoryItem[]; onAdd:()=>void; onStatus:(value:string)=>void; onAll:()=>void }) { const m=dashboardMetrics(items); const cards=[['Total Inventory',m.totalInventory,'Units on hand'],['Active Listings',m.activeListings,'Live listings'],['Sold Today',m.soldToday,'Completed today'],['Sold This Week',m.soldThisWeek,'Last seven days'],['Inventory Cost',money(m.inventoryCost),'Capital invested'],['Inventory Value',money(m.inventoryValue),'Expected revenue'],['Estimated Profit',money(m.estimatedProfit),'After shipping and fees']]; return <><section className="stats">{cards.map(([label,value,detail])=><KpiCard key={String(label)} label={String(label)} value={value} detail={String(detail)}/>)}</section><section className="dashboard-row"><RecentActivity items={items}/><QuickActions onAdd={onAdd} onStatus={onStatus} onAll={onAll}/></section></>; }
