import{useEffect,useMemo,useState}from'react';
import{AlertTriangle,BrainCircuit,Check,ChevronLeft,ChevronRight,History,ImageOff,Pause,Play,RefreshCw,Search,Settings2,X}from'lucide-react';
import type{AIHistory as AIHistoryType,AIResponse,AISettings,AISuggestion,AITask}from'../../../shared/ai';
import type{ListingQueueItem}from'../../../shared/listings';
import{isStale}from'../../domain/aiListing';
import{aiService,defaultAISettings}from'../../services/aiService';
import{listingService}from'../../services/listingService';
const tasks:Array<[AITask,string]>=[['title','Generate title'],['description','Generate description'],['category','Suggest category'],['specifics','Suggest item specifics'],['condition','Draft condition notes'],['keywords','Suggest keywords'],['pricing','Suggest pricing range'],['shipping','Suggest shipping profile'],['missing',"What's missing?"],['full-draft','Generate complete listing draft']];
function SuggestionCard({suggestion,response,onUpdate}:{suggestion:AISuggestion;response:AIResponse;onUpdate:(s:AISuggestion)=>void}){const[editing,setEditing]=useState(false),[value,setValue]=useState(suggestion.value);const set=(status:AISuggestion['status'])=>onUpdate({...suggestion,value,status});return <article className={'ai-suggestion '+suggestion.status.toLowerCase()}><div className="ai-suggestion-head"><div><span className="ai-badge">AI-generated</span><b>{suggestion.field}</b></div><span>{response.provider} · {response.model}</span></div>{editing?<textarea value={value} onChange={e=>setValue(e.target.value)}/>:<pre>{suggestion.value}</pre>}<div className="evidence-row"><span>{suggestion.evidence}</span><span>{Math.round(suggestion.confidence*100)}% evidence</span><span>{suggestion.field==='title'?suggestion.value.length+'/80':''}</span></div><small>Sources: {suggestion.sources.join(', ')||'None'}</small>{suggestion.warnings.map(w=><p className="ai-warning" key={w}><AlertTriangle/>{w}</p>)}<div className="ai-review-actions"><button onClick={()=>set('Accepted')}><Check/>Accept</button><button onClick={()=>{if(editing)set('Edited');setEditing(!editing)}}>{editing?'Save & accept':'Edit'}</button><button onClick={()=>set('Rejected')}><X/>Reject</button></div></article>}
export function AIListingAssistant(){
 const[queue,setQueue]=useState<ListingQueueItem[]>([]),[selected,setSelected]=useState(0),[query,setQuery]=useState(''),[filter,setFilter]=useState('All'),[settings,setSettings]=useState<AISettings>(()=>{try{return{...defaultAISettings,...JSON.parse(sessionStorage.getItem('metro-ai-settings')??'{}')}}catch{return defaultAISettings}});
 const[response,setResponse]=useState<AIResponse>(),[history,setHistory]=useState<AIHistoryType[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[showSettings,setShowSettings]=useState(false),[batch,setBatch]=useState<number[]>([]),[batchState,setBatchState]=useState<'idle'|'running'|'paused'>('idle');
 useEffect(()=>{void listingService.queue().then(setQueue)},[]);const visible=useMemo(()=>queue.filter(i=>(!query||[i.sku,i.title,i.brand].join(' ').toLowerCase().includes(query.toLowerCase()))&&(filter==='All'||filter==='Low readiness'?filter==='All'||i.readiness<50:filter==='Ready'?i.readiness===100:i.listing.status===filter)),[queue,query,filter]);const item=visible[Math.min(selected,Math.max(0,visible.length-1))];
 useEffect(()=>{setResponse(undefined);if(item)void aiService.history(item.inventoryId).then(setHistory)},[item?.inventoryId]);
 const request=(task:AITask)=>item?{inventoryId:item.inventoryId,task,item,candidateCount:settings.titleCandidates,tone:settings.tone}:undefined;
 const generate=async(task:AITask)=>{const input=request(task);if(!input)return;setBusy(true);setError('');try{setResponse(await aiService.generate(input,settings))}catch(e){setError(e instanceof Error?e.message:'Provider unavailable. Retry or use the offline provider.')}finally{setBusy(false)}};
 const update=async(s:AISuggestion)=>{if(!response)return;setResponse({...response,suggestions:response.suggestions.map(x=>x.id===s.id?s:x)});if(response.sessionId)await aiService.feedback(response.sessionId,s.id,s.status,s.value)};
 const saveSettings=(next:AISettings)=>{setSettings(next);sessionStorage.setItem('metro-ai-settings',JSON.stringify(next))};
 const runBatch=async()=>{setBatchState('running');for(const id of batch){if(batchState==='paused')break;const target=queue.find(q=>q.inventoryId===id);if(!target)continue;try{await aiService.generate({inventoryId:id,task:'missing',item:target},settings)}catch{/* per-item retry remains available */}}setBatchState('idle')};
 return <section className="ai-workspace"><header><div><p className="eyebrow">V0.5.0 DEVELOPMENT</p><h1><BrainCircuit/>AI Listing Assistant</h1><p>Provider-neutral, review-first listing assistance. Nothing is written without acceptance.</p></div><div className="ai-header-actions"><button className="secondary" onClick={()=>document.querySelector<HTMLButtonElement>('.sidebar nav button:nth-child(4)')?.click()}>Back to Listing Workspace</button><button className="secondary" onClick={()=>setShowSettings(!showSettings)}><Settings2/>Settings</button></div></header>
 {showSettings&&<section className="ai-settings"><h2>AI Settings & Privacy</h2><div className="ai-settings-grid"><label>Provider<select value={settings.provider} onChange={e=>saveSettings({...settings,provider:e.target.value})}><option value="local">Local deterministic</option><option value="openai">OpenAI adapter</option></select></label><label>Model<input value={settings.model} onChange={e=>saveSettings({...settings,model:e.target.value})}/></label><label>Timeout (ms)<input type="number" value={settings.timeoutMs} onChange={e=>saveSettings({...settings,timeoutMs:Number(e.target.value)})}/></label><label>Default tone<input value={settings.tone} onChange={e=>saveSettings({...settings,tone:e.target.value})}/></label><label>Title candidates<input type="number" min="1" max="3" value={settings.titleCandidates} onChange={e=>saveSettings({...settings,titleCandidates:Number(e.target.value)})}/></label><label><input type="checkbox" checked={settings.imageAnalysis} disabled/>Image analysis opt-in (provider unavailable)</label></div><p>Credentials are read only by the main process from the environment and are never exposed here. Photos are never uploaded automatically.</p><div><button onClick={()=>void aiService.test(settings).then(r=>setError(r.message))}>Test connection</button><button onClick={()=>void aiService.clearHistory().then(()=>setHistory([]))}>Clear AI history</button></div></section>}
 <div className="ai-layout"><aside className="ai-queue"><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search assistant queue…"/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option>All</option><option>Low readiness</option><option>Ready</option><option>Purchased</option></select>{visible.map((q,n)=><button className={q.inventoryId===item?.inventoryId?'selected':''} key={q.inventoryId} onClick={()=>setSelected(n)}><input aria-label={'Select '+q.sku+' for batch'} type="checkbox" checked={batch.includes(q.inventoryId)} onChange={e=>{e.stopPropagation();setBatch(v=>e.target.checked?[...v,q.inventoryId]:v.filter(id=>id!==q.inventoryId))}}/><span><b>{q.sku}</b>{q.title}</span><strong>{q.readiness}%</strong></button>)}</aside>
 {item?<main className="ai-main"><div className="ai-item-nav"><button disabled={!selected} onClick={()=>setSelected(v=>v-1)}><ChevronLeft/>Previous</button><div><b>{item.title}</b><span>{item.sku} · {item.brand||'Brand missing'} · {item.category||'Category missing'}</span></div><button disabled={selected>=visible.length-1} onClick={()=>setSelected(v=>v+1)}>Next<ChevronRight/></button></div><div className="ai-context"><div className="ai-photo">{item.primaryPhotoUrl?<img src={item.primaryPhotoUrl} alt="Selected product"/>:<><ImageOff/><span>No primary photo</span></>}</div><article><h2>Source data</h2><dl><dt>Condition</dt><dd>{item.condition||'Missing'}</dd><dt>Size</dt><dd>{item.size||'Missing'}</dd><dt>Color</dt><dd>{item.color||'Missing'}</dd><dt>Expected price</dt><dd>{item.listPrice?'$'+item.listPrice.toFixed(2):'Missing'}</dd></dl></article><article><h2>Validation</h2><p>{item.missing.length?item.missing.join(', '):'No readiness blockers'}</p><b>{item.readiness}% ready</b></article></div>
 <section className="ai-generation"><h2>Generate suggestions</h2><p>Choose a task. Generation never starts automatically.</p><div className="ai-task-grid">{tasks.map(([key,label])=><button disabled={busy} key={key} onClick={()=>void generate(key)}>{busy?<RefreshCw className="spin"/>:<BrainCircuit/>}{label}</button>)}</div></section>{error&&<div className="ai-error" role="alert"><AlertTriangle/>{error}</div>}
 {response&&<section className="ai-results"><div className="ai-results-head"><div><h2>{response.suggestions.length} generated candidates</h2><p>{new Date(response.generatedAt).toLocaleString()} · Review every field before acceptance.</p></div>{isStale(response,request('full-draft')!)&&<span className="stale">Stale source data</span>}</div>{response.warnings.map(w=><p className="ai-warning" key={w}>{w}</p>)}<div className="ai-suggestions">{response.suggestions.map(s=><SuggestionCard key={s.id} suggestion={s} response={response} onUpdate={s=>void update(s)}/>)}</div></section>}
 <section className="ai-batch"><h2>Safe batch queue</h2><p>{batch.length} selected · Missing-information analysis only · concurrency 1 · no automatic acceptance</p><button disabled={!batch.length||batchState==='running'} onClick={()=>void runBatch()}><Play/>Start</button><button disabled={batchState!=='running'} onClick={()=>setBatchState('paused')}><Pause/>Pause</button></section><section className="ai-history"><h2><History/>Generation history</h2>{history.length?history.map(h=><div key={h.id}><b>{h.task}</b><span>{h.provider} · {new Date(h.generatedAt).toLocaleString()} · {h.status}</span></div>):<p>No saved generations for this item.</p>}</section></main>:<div className="listing-empty">No inventory items match this queue.</div>}</div></section>}
