import { useEffect,useRef,useState } from 'react';
import { ArrowLeft,ArrowRight,ImagePlus,Star,Trash2,UploadCloud } from 'lucide-react';
import type { InventoryItem } from '../../../shared/inventory';
import type { InventoryPhoto } from '../../../shared/photos';
import { photoService,preparePhoto } from '../../services/photoService';

export function PhotoManager({items,initialInventoryId,onInventoryChanged}:{items:InventoryItem[];initialInventoryId?:number;onInventoryChanged:()=>Promise<void>}){
 const workflow=(()=>{try{return JSON.parse(sessionStorage.getItem('metro-workflow')??'{}')as{ids?:number[];label?:string;source?:string}}catch{return{}}})();const actionItems=workflow.ids?items.filter(item=>workflow.ids?.includes(item.id)):items;
 const[selectedId,setSelectedId]=useState(initialInventoryId??actionItems[0]?.id??0);const[photos,setPhotos]=useState<InventoryPhoto[]>([]);const[selectedPhoto,setSelectedPhoto]=useState<number>();const[busy,setBusy]=useState(false);const[errors,setErrors]=useState<string[]>([]);const input=useRef<HTMLInputElement>(null);
 const load=async(id=selectedId)=>{if(!id){setPhotos([]);return;}try{const next=await photoService.list(id);setPhotos(next);setSelectedPhoto(current=>next.some(p=>p.id===current)?current:next[0]?.id);setErrors([]);}catch(error){setErrors([error instanceof Error?error.message:'Photos could not be loaded.']);}};
 useEffect(()=>{void load();},[selectedId]);const current=photos.find(photo=>photo.id===selectedPhoto)??photos[0];
 const importFiles=async(files:FileList|File[])=>{if(!selectedId)return;setBusy(true);const failures:string[]=[];for(const file of Array.from(files)){try{await photoService.import(await preparePhoto(selectedId,file));}catch(error){failures.push(error instanceof Error?error.message:`${file.name}: import failed.`);}}setErrors(failures);await load();await onInventoryChanged();setBusy(false);if(input.current)input.current.value='';};
 const setPrimary=async(photoId:number)=>{setPhotos(await photoService.setPrimary(selectedId,photoId));setSelectedPhoto(photoId);await onInventoryChanged();};
 const remove=async(photoId:number)=>{if(!confirm('Remove this photo from the inventory item?'))return;setPhotos(await photoService.delete(selectedId,photoId));await onInventoryChanged();};
 const move=async(photoId:number,direction:-1|1)=>{const ordered=[...photos];const from=ordered.findIndex(p=>p.id===photoId);const to=from+direction;if(from<0||to<0||to>=ordered.length)return;[ordered[from],ordered[to]]=[ordered[to],ordered[from]];setPhotos(await photoService.reorder(selectedId,ordered.map(p=>p.id)));};
 return <section className="photo-manager">{workflow.source==='analytics'&&<div className="workflow-banner"><span>Filtered from Analytics: <b>{workflow.label}</b> · {actionItems.length} affected records</span><button onClick={()=>{sessionStorage.removeItem('metro-workflow');document.querySelector<HTMLButtonElement>('.sidebar nav button:nth-child(7)')?.click()}}>Back to Analytics</button></div>}<div className="photo-toolbar"><div><p className="eyebrow">SPRINT 4.1</p><h1>Photo Manager</h1><p>Prepare inventory photography for fast, consistent listings.</p></div><label>Inventory item<select value={selectedId} onChange={event=>setSelectedId(Number(event.target.value))}>{actionItems.map(item=><option key={item.id} value={item.id}>{item.sku} — {item.title}</option>)}</select></label></div>
 {errors.length>0&&<div className="photo-errors" role="alert"><strong>Some photos need attention</strong>{errors.map((error,index)=><div key={index}>{error}</div>)}</div>}
 {!actionItems.length?<div className="photo-empty"><ImagePlus/><h2>No inventory records match this workflow</h2></div>:<div className="photo-layout"><div className="photo-stage">{current?.imageUrl?<><img src={current.imageUrl} alt={current.originalFileName}/><div className="photo-stage-meta"><span>{current.originalFileName}</span>{current.isPrimary&&<b><Star size={14}/>Primary photo</b>}</div></>:<div className="photo-empty"><ImagePlus size={42}/><h2>No photos yet</h2><p>Import JPEG, PNG, or WebP images for this item.</p></div>}</div>
 <aside className="photo-import"><div className="drop-zone" onDragOver={event=>event.preventDefault()} onDrop={event=>{event.preventDefault();void importFiles(event.dataTransfer.files);}}><UploadCloud size={34}/><strong>{busy?'Importing photos…':'Drop product photos here'}</strong><span>JPEG, PNG, or WebP · up to 20 MB each</span><button className="primary" disabled={busy} onClick={()=>input.current?.click()}>Choose photos</button><input ref={input} hidden type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={event=>event.target.files&&void importFiles(event.target.files)}/></div><div className="photo-summary"><b>{photos.length}</b><span>photos attached</span></div></aside></div>}
 {photos.length>0&&<div className="photo-gallery" aria-label="Attached photos">{photos.map((photo,index)=><article key={photo.id} className={photo.id===current?.id?'selected':''}><button className="thumb" onClick={()=>setSelectedPhoto(photo.id)} aria-label={`Preview ${photo.originalFileName}`}><img src={photo.thumbnailUrl||photo.imageUrl} alt=""/>{photo.isPrimary&&<span><Star size={12}/>Primary</span>}</button><div className="photo-actions"><button title="Move left" disabled={index===0||photo.isPrimary} onClick={()=>void move(photo.id,-1)}><ArrowLeft/></button><button title="Move right" disabled={index===photos.length-1||photo.isPrimary} onClick={()=>void move(photo.id,1)}><ArrowRight/></button><button title="Set primary" disabled={photo.isPrimary} onClick={()=>void setPrimary(photo.id)}><Star/></button><button title="Remove photo" onClick={()=>void remove(photo.id)}><Trash2/></button></div></article>)}</div>}
 </section>;
}
