import { ArrowUpDown, Pencil, Search, Trash2, X } from 'lucide-react';
import type { InventoryItem, InventoryStatus } from '../../../shared/inventory';
import { calculateItemFinancials } from '../../domain/inventory';

type SortKey = keyof InventoryItem;
const money = (value:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(value);

export function InventoryToolbar({ query, status, onQuery, onStatus }:{query:string;status:string;onQuery:(v:string)=>void;onStatus:(v:string)=>void}) { return <div className="inventory-tools"><label className="search"><Search size={17}/><input value={query} onChange={e=>onQuery(e.target.value)} placeholder="Search item, SKU, bin, rack, shelf…"/></label><StatusFilter value={status} onChange={onStatus}/></div>; }
export function StatusFilter({value,onChange}:{value:string;onChange:(v:string)=>void}) { return <select value={value} onChange={e=>onChange(e.target.value)}><option>All</option><option>Draft</option><option>Active</option><option>Sold</option><option>Archived</option></select>; }
export function InventoryEditCell({value,onChange,className='',type='text'}:{value:string|number;onChange:(v:string)=>void;className?:string;type?:string}) { return <input className={`cell-input ${className}`} type={type} value={value} onChange={e=>onChange(e.target.value)}/>; }

export function InventoryRow({item,editing,onEdit,onCancel,onSave,onDelete,onChange}:{item:InventoryItem;editing:InventoryItem|null;onEdit:()=>void;onCancel:()=>void;onSave:()=>void;onDelete:()=>void;onChange:(item:InventoryItem)=>void}) { const active=editing?.id===item.id; const row=active&&editing?editing:item; const f=calculateItemFinancials(row); if(active&&editing) return <tr><td><InventoryEditCell className="sku" value={row.sku} onChange={v=>onChange({...row,sku:v})}/></td><td><div className="stacked-inputs"><InventoryEditCell value={row.title} onChange={v=>onChange({...row,title:v})}/><InventoryEditCell className="muted" value={row.brand} onChange={v=>onChange({...row,brand:v})}/></div></td><td><select className="cell-input" value={row.status} onChange={e=>onChange({...row,status:e.target.value as InventoryStatus})}><option>Draft</option><option>Active</option><option>Sold</option><option>Archived</option></select></td>{(['quantity','purchasePrice','listPrice'] as const).map(key=><td key={key}><InventoryEditCell className="number" type="number" value={row[key]} onChange={v=>onChange({...row,[key]:Number(v)})}/></td>)}<td>{money(f.netProfit)}</td><td>{f.roi.toFixed(1)}%</td>{(['bin','rack','shelf','drawer'] as const).map(key=><td key={key}><InventoryEditCell className="storage" value={row[key]} onChange={v=>onChange({...row,[key]:v})}/></td>)}<td><div className="row-actions"><button className="save" onClick={onSave}>Save</button><button className="icon" onClick={onCancel} aria-label="Cancel"><X size={16}/></button></div></td></tr>; return <tr><td className="mono">{item.sku}</td><td><b>{item.title}</b><span>{item.brand} · {item.category} · {item.size}</span></td><td><em className={item.status.toLowerCase()}>{item.status}</em></td><td>{item.quantity}</td><td>{money(item.purchasePrice)}</td><td>{money(item.listPrice)}</td><td className={item.profit>=0?'positive':'negative'}>{money(item.profit)}</td><td>{item.roi.toFixed(1)}%</td><td>{item.bin||'—'}</td><td>{item.rack||'—'}</td><td>{item.shelf||'—'}</td><td>{item.drawer||'—'}</td><td><div className="row-actions"><button className="icon" onClick={onEdit} aria-label="Edit"><Pencil size={16}/></button><button className="icon danger" onClick={onDelete} aria-label="Delete"><Trash2 size={16}/></button></div></td></tr>; }

export function InventoryTable({items,editing,sort,onSort,onEdit,onCancel,onSave,onDelete,onChange}:{items:InventoryItem[];editing:InventoryItem|null;sort:{key:SortKey;direction:1|-1};onSort:(k:SortKey)=>void;onEdit:(i:InventoryItem)=>void;onCancel:()=>void;onSave:()=>void;onDelete:(id:number)=>void;onChange:(i:InventoryItem)=>void}) { const heads=[['sku','SKU'],['title','Item'],['status','Status'],['quantity','Qty'],['purchasePrice','Purchase'],['listPrice','List'],['profit','Net Profit'],['roi','ROI'],['bin','Bin'],['rack','Rack'],['shelf','Shelf'],['drawer','Drawer']] as Array<[SortKey,string]>; return <div className="table-wrap"><table><thead><tr>{heads.map(([key,label])=><th key={key}><button onClick={()=>onSort(key)}>{label}<ArrowUpDown size={12}/></button></th>)}<th>Actions</th></tr></thead><tbody>{items.map(item=><InventoryRow key={item.id} item={item} editing={editing} onEdit={()=>onEdit(item)} onCancel={onCancel} onSave={onSave} onDelete={()=>onDelete(item.id)} onChange={onChange}/>)}</tbody></table></div>; }

export function InventoryPage(props:{items:InventoryItem[];query:string;status:string;editing:InventoryItem|null;sort:{key:SortKey;direction:1|-1};onQuery:(v:string)=>void;onStatus:(v:string)=>void;onSort:(k:SortKey)=>void;onEdit:(i:InventoryItem)=>void;onCancel:()=>void;onSave:()=>void;onDelete:(id:number)=>void;onChange:(i:InventoryItem)=>void}) { return <section className="panel inventory-panel"><div className="panel-head"><div><h2>Inventory Workspace</h2><p>Search storage locations, filter status, sort columns, and edit records inline.</p></div><InventoryToolbar query={props.query} status={props.status} onQuery={props.onQuery} onStatus={props.onStatus}/></div><InventoryTable {...props}/></section>; }
